version: '3'

services:
  sample:
    build: .
    image: docker-nodejs-sampleapp
    ports:
      - '5000:5000'
    command: npm start

  sample-dev:
    image: eabay/nodejs:dev
    ports:
      - '5000:5000'
    volumes:
      - .:/app
