FROM mhart/alpine-node

ENV NODE_ENV production

RUN apk add --no-cache supervisor && \
    rm -rf /tmp/*

COPY supervisor.conf /etc/supervisor.d/app.ini

ONBUILD COPY . /app
WORKDIR /app

VOLUME /logs

CMD ["/usr/bin/supervisord", "-n"]
